[build]
  command = "npm run build"  # Command to build your project
  publish = "build"          # Folder for frontend’s static files
  functions = "functions"    # Folder for serverless functions

[[redirects]]
  from = "/api/*"            # Route API requests to functions
  to = "/.netlify/functions/:splat"
  status = 200