[build]
  publish = "build"       # Correct folder for frontend’s static files
  functions = "functions" # Folder with serverless functions

[[redirects]]
  from = "/api/*"         # Route API requests to functions
  to = "/.netlify/functions/:splat"
  status = 200

  [build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200